-- DeepSeek Club - events & projects 初始化脚本
-- 说明：请在执行 server/db.sql 后，再执行本脚本。

USE deepseek_club;

-- events 表：AI 活动（含人工提交审核流）
CREATE TABLE IF NOT EXISTS events (
  id VARCHAR(64) PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  `desc` TEXT,
  full_desc TEXT,
  event_type VARCHAR(30) NOT NULL,
  event_mode VARCHAR(30) NOT NULL,
  event_status VARCHAR(30) NOT NULL,
  city VARCHAR(30) NOT NULL,
  cover_image VARCHAR(255) NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  location VARCHAR(255) NULL,
  online_url VARCHAR(255) NULL,
  organizer VARCHAR(100) NOT NULL,
  organizer_logo VARCHAR(255) NULL,
  speakers JSON NULL,
  tags JSON NULL,
  max_participants INT NULL,
  current_participants INT NULL,
  price VARCHAR(50) NULL,
  highlights JSON NULL,
  agenda JSON NULL,
  sponsors JSON NULL,
  registration_url VARCHAR(255) NULL,
  likes INT DEFAULT 0,
  approval_status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'approved',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_events_start (start_date),
  INDEX idx_events_status (event_status),
  INDEX idx_events_approval (approval_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI 活动表';

-- event_registrations 表：活动报名记录
CREATE TABLE IF NOT EXISTS event_registrations (
  id INT PRIMARY KEY AUTO_INCREMENT,
  event_id VARCHAR(64) NOT NULL,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(200) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  company VARCHAR(200) NULL,
  role VARCHAR(100) NULL,
  team_name VARCHAR(100) NULL,
  team_size VARCHAR(50) NULL,
  ticket_count INT NOT NULL DEFAULT 1,
  notes TEXT NULL,
  payment_status ENUM('free','paid','unpaid','success','pending') NOT NULL DEFAULT 'free',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_reg_event (event_id),
  CONSTRAINT fk_event_reg_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='活动报名记录';

-- projects 表：AI 开源项目库（含人工提交审核流）
CREATE TABLE IF NOT EXISTS projects (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  full_name VARCHAR(200) NOT NULL,
  category VARCHAR(50) NOT NULL,
  description TEXT,
  long_description MEDIUMTEXT,
  language VARCHAR(50) NOT NULL,
  stars INT DEFAULT 0,
  forks INT DEFAULT 0,
  issues INT DEFAULT 0,
  contributors INT DEFAULT 0,
  license VARCHAR(80) NULL,
  last_update DATE NULL,
  created_at DATE NULL,
  topics JSON NULL,
  github_url VARCHAR(255) NOT NULL,
  website_url VARCHAR(255) NULL,
  logo_url VARCHAR(255) NULL,
  is_weekly_pick TINYINT(1) DEFAULT 0,
  is_editor_choice TINYINT(1) DEFAULT 0,
  editor_comment TEXT NULL,
  trend_stars_7d INT DEFAULT 0,
  likes INT DEFAULT 0,
  approval_status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'approved',
  submitted_reason TEXT NULL,
  submitted_tags JSON NULL,
  submitted_website_url VARCHAR(255) NULL,
  created_at_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_projects_category (category),
  INDEX idx_projects_approval (approval_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI 开源项目库表';

-- ========= Seed: events =========
INSERT INTO events (
  id, title, `desc`, full_desc, event_type, event_mode, event_status, city,
  cover_image, start_date, end_date, location, online_url, organizer, organizer_logo,
  speakers, tags, max_participants, current_participants, price,
  highlights, agenda, sponsors, registration_url,
  likes, approval_status
) VALUES (
  'deepseek-hackathon-2026',
  'DeepSeek 全球开源黑客松 2026',
  '48小时极限编程挑战，基于 DeepSeek 模型构建创新应用，争夺 50 万奖金池',
  'DeepSeek 全球开源黑客松 2026 是深求社区年度旗舰活动，邀请全球开发者在 48 小时内基于 DeepSeek 系列模型构建创新应用。本次黑客松设置了 50 万元总奖金池，涵盖最佳创新奖、最佳技术奖、最佳商业价值奖等多个赛道。\n\n## 赛道设置\n- **AI Agent 赛道**：构建基于 DeepSeek 的智能代理应用\n- **代码智能赛道**：开发代码辅助、审查、生成类工具\n- **多模态赛道**：利用 DeepSeek-VL 系列构建视觉+语言应用\n- **开放赛道**：不限主题，自由发挥创意\n\n## 参赛要求\n- 1-5 人组队参赛\n- 项目必须使用至少一个 DeepSeek 模型\n- 代码需在活动期间完成并开源\n- 提交完整的项目演示和文档',
  'hackathon',
  'hybrid',
  'registering',
  'beijing',
  'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&q=80',
  '2026-04-18',
  '2026-04-20',
  '北京·中关村国际创新中心 / 线上同步',
  'https://deepseek.club/hackathon-2026',
  '深求社区',
  '',
  '[{"name":"张明远","title":"首席科学家","avatar":"","company":"DeepSeek"},{"name":"李思涵","title":"开源生态负责人","avatar":"","company":"深求社区"},{"name":"王浩然","title":"CTO","avatar":"","company":"AI Startup"}]',
  '["黑客松","开源","AI应用","奖金"]',
  500,
  347,
  '免费',
  '["50万奖金池","48小时极限挑战","顶级导师指导","投资人现场对接"]',
  '[{"time":"04/18 09:00","title":"开幕式与赛题发布","speaker":"李思涵"},{"time":"04/18 10:00","title":"DeepSeek API 技术培训","speaker":"张明远"},{"time":"04/18 11:00","title":"自由组队与开发开始"},{"time":"04/19 14:00","title":"中期检查与导师辅导"},{"time":"04/20 10:00","title":"项目提交截止"},{"time":"04/20 14:00","title":"路演与评审"},{"time":"04/20 17:00","title":"颁奖典礼","speaker":"王浩然"}]',
  '["DeepSeek","阿里云","华为云","红杉资本"]',
  'https://deepseek.club/hackathon-2026',
  2340,
  'approved'
);
INSERT INTO events (
  id, title, `desc`, full_desc, event_type, event_mode, event_status, city,
  cover_image, start_date, end_date, location, online_url, organizer, organizer_logo,
  speakers, tags, max_participants, current_participants, price,
  highlights, agenda, sponsors, registration_url,
  likes, approval_status
) VALUES (
  'deepseek-r1-deep-dive',
  'DeepSeek-R1 深度解析：强化学习如何重塑推理',
  'DeepSeek 核心研究员亲自讲解 R1 模型的训练方法论与技术突破',
  '本次讲座由 DeepSeek 核心研究团队成员主讲，深入解析 DeepSeek-R1 模型背后的强化学习训练方法论。从 GRPO 算法原理到大规模 RL 训练的工程实践，从思维链推理的涌现到数学竞赛级能力的达成，全方位揭秘 R1 的技术路径。\n\n## 讲座内容\n- R1 的训练范式：从 SFT 到 RL 的演进\n- GRPO 算法详解与实现细节\n- 思维链推理能力的涌现机制\n- 蒸馏技术：如何将 R1 能力迁移到小模型\n- Q&A 互动环节',
  'lecture',
  'online',
  'upcoming',
  'online',
  'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80',
  '2026-03-28',
  '2026-03-28',
  '线上直播',
  'https://deepseek.club/live/r1-deep-dive',
  '深求社区',
  '',
  '[{"name":"陈博文","title":"高级研究员","avatar":"","company":"DeepSeek"},{"name":"刘雨晨","title":"算法工程师","avatar":"","company":"DeepSeek"}]',
  '["R1","强化学习","推理","技术讲座"]',
  5000,
  3280,
  '免费',
  '["核心团队主讲","技术深度解析","实时Q&A","录播回放"]',
  '[{"time":"19:00","title":"开场介绍"},{"time":"19:10","title":"R1 训练范式解析","speaker":"陈博文"},{"time":"19:50","title":"GRPO 算法与工程实践","speaker":"刘雨晨"},{"time":"20:30","title":"蒸馏技术与小模型部署","speaker":"陈博文"},{"time":"21:00","title":"Q&A 互动"}]',
  '["DeepSeek"]',
  'https://deepseek.club/live/r1-deep-dive',
  1856,
  'approved'
);
INSERT INTO events (
  id, title, `desc`, full_desc, event_type, event_mode, event_status, city,
  cover_image, start_date, end_date, location, online_url, organizer, organizer_logo,
  speakers, tags, max_participants, current_participants, price,
  highlights, agenda, sponsors, registration_url,
  likes, approval_status
) VALUES (
  'ai-agent-workshop',
  'AI Agent 实战工作坊：从零构建智能助手',
  '手把手教你基于 DeepSeek API 构建多工具调用的 AI Agent',
  '本工作坊面向有一定编程基础的开发者，从零开始构建一个具备多工具调用能力的 AI Agent。学员将学习 Function Calling、RAG、记忆管理等核心技术，并在导师指导下完成一个完整的 Agent 项目。\n\n## 学习内容\n- AI Agent 架构设计\n- DeepSeek API Function Calling 实战\n- RAG 检索增强生成\n- 多轮对话与记忆管理\n- Agent 部署与优化',
  'workshop',
  'hybrid',
  'registering',
  'shanghai',
  'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&q=80',
  '2026-04-05',
  '2026-04-06',
  '上海·张江人工智能岛 / 线上同步',
  'https://deepseek.club/workshop/ai-agent',
  '深求社区 × AI 创新实验室',
  '',
  '[{"name":"赵天宇","title":"技术总监","avatar":"","company":"AI 创新实验室"},{"name":"孙晓峰","title":"高级工程师","avatar":"","company":"深求社区"}]',
  '["Agent","工作坊","实战","API"]',
  120,
  89,
  '¥299',
  '["动手实操","导师1对1指导","完整项目产出","结业证书"]',
  '[{"time":"Day1 09:00","title":"Agent 架构设计与 API 入门","speaker":"赵天宇"},{"time":"Day1 14:00","title":"Function Calling 实战","speaker":"孙晓峰"},{"time":"Day2 09:00","title":"RAG 与记忆管理","speaker":"赵天宇"},{"time":"Day2 14:00","title":"项目整合与部署","speaker":"孙晓峰"},{"time":"Day2 16:00","title":"项目展示与点评"}]',
  '["DeepSeek","阿里云"]',
  'https://deepseek.club/workshop/ai-agent',
  967,
  'approved'
);
INSERT INTO events (
  id, title, `desc`, full_desc, event_type, event_mode, event_status, city,
  cover_image, start_date, end_date, location, online_url, organizer, organizer_logo,
  speakers, tags, max_participants, current_participants, price,
  highlights, agenda, sponsors, registration_url,
  likes, approval_status
) VALUES (
  'shenzhen-ai-meetup-03',
  '深圳 AI 开发者聚会 · 三月场',
  '深圳本地 AI 开发者面对面交流，分享项目经验与行业洞察',
  '深圳 AI 开发者月度聚会，每月一期，为深圳及大湾区的 AI 开发者提供面对面交流的机会。本期主题为「DeepSeek 在企业落地的实践经验」，邀请了三位在不同行业成功落地 DeepSeek 的技术负责人分享经验。\n\n## 本期主题\n- DeepSeek 在金融风控中的应用\n- 基于 DeepSeek-Coder 的代码审查系统\n- DeepSeek-VL 在电商场景的实践',
  'meetup',
  'offline',
  'upcoming',
  'shenzhen',
  'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
  '2026-03-29',
  '2026-03-29',
  '深圳·南山科技园 WeWork',
  NULL,
  '深求社区深圳分会',
  '',
  '[{"name":"林志远","title":"AI 架构师","avatar":"","company":"某金融科技公司"},{"name":"黄嘉琪","title":"技术负责人","avatar":"","company":"某电商平台"},{"name":"周明","title":"研发总监","avatar":"","company":"某软件公司"}]',
  '["聚会","深圳","企业落地","经验分享"]',
  80,
  62,
  '免费',
  '["面对面交流","行业案例分享","自由社交时间","精美茶歇"]',
  '[{"time":"14:00","title":"签到与自由交流"},{"time":"14:30","title":"DeepSeek 在金融风控中的应用","speaker":"林志远"},{"time":"15:10","title":"基于 DeepSeek-Coder 的代码审查","speaker":"周明"},{"time":"15:50","title":"茶歇与交流"},{"time":"16:10","title":"DeepSeek-VL 在电商的实践","speaker":"黄嘉琪"},{"time":"16:50","title":"自由讨论与社交"}]',
  '["深求社区","WeWork"]',
  'https://deepseek.club/meetup/shenzhen-03',
  534,
  'approved'
);
INSERT INTO events (
  id, title, `desc`, full_desc, event_type, event_mode, event_status, city,
  cover_image, start_date, end_date, location, online_url, organizer, organizer_logo,
  speakers, tags, max_participants, current_participants, price,
  highlights, agenda, sponsors, registration_url,
  likes, approval_status
) VALUES (
  'global-ai-conference-2026',
  '2026 全球 AI 开源生态大会',
  '汇聚全球顶尖 AI 研究者与开发者，探讨开源 AI 的未来',
  '2026 全球 AI 开源生态大会是深求社区主办的年度旗舰大会，汇聚来自全球的 AI 研究者、开发者、创业者和投资人。大会设置主论坛和多个分论坛，涵盖大模型技术、AI Agent、多模态、AI 安全等前沿话题。\n\n## 大会亮点\n- 20+ 主题演讲\n- 8 个专题分论坛\n- 圆桌对话与 Panel 讨论\n- 开源项目展示区\n- 创业路演与投资对接',
  'conference',
  'hybrid',
  'registering',
  'hangzhou',
  'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800&q=80',
  '2026-06-15',
  '2026-06-17',
  '杭州·未来科技城国际会议中心 / 线上同步',
  'https://deepseek.club/conference-2026',
  '深求社区',
  '',
  '[{"name":"梁峰","title":"创始人","avatar":"","company":"DeepSeek"},{"name":"Sarah Chen","title":"VP of Research","avatar":"","company":"AI Research Lab"},{"name":"田中太郎","title":"教授","avatar":"","company":"东京大学"},{"name":"Michael Wang","title":"Partner","avatar":"","company":"红杉资本"}]',
  '["大会","开源生态","前沿技术","投资对接"]',
  3000,
  1856,
  '¥599（早鸟 ¥399）',
  '["20+ 主题演讲","8 个分论坛","开源项目展示","投资对接"]',
  '[{"time":"Day1 09:00","title":"开幕式与主旨演讲","speaker":"梁峰"},{"time":"Day1 10:30","title":"大模型技术前沿","speaker":"Sarah Chen"},{"time":"Day1 14:00","title":"分论坛（AI Agent / 多模态 / AI 安全 / 开源治理）"},{"time":"Day2 09:00","title":"AI 开源生态的全球化","speaker":"田中太郎"},{"time":"Day2 14:00","title":"创业路演与投资对接","speaker":"Michael Wang"},{"time":"Day3 09:00","title":"开源项目展示与评选"},{"time":"Day3 15:00","title":"闭幕式与颁奖"}]',
  '["DeepSeek","阿里巴巴","腾讯","华为","红杉资本","高瓴资本"]',
  'https://deepseek.club/conference-2026',
  4560,
  'approved'
);
INSERT INTO events (
  id, title, `desc`, full_desc, event_type, event_mode, event_status, city,
  cover_image, start_date, end_date, location, online_url, organizer, organizer_logo,
  speakers, tags, max_participants, current_participants, price,
  highlights, agenda, sponsors, registration_url,
  likes, approval_status
) VALUES (
  'multimodal-sharing',
  '多模态 AI 技术分享：从 DeepSeek-VL 到实际应用',
  '探索视觉语言模型的最新进展与产业应用案例',
  '本次技术分享聚焦多模态 AI 领域，从 DeepSeek-VL 系列模型的技术原理出发，深入探讨视觉语言模型在文档理解、图像分析、视频理解等场景的应用实践。\n\n## 分享内容\n- DeepSeek-VL2 架构解析\n- 视觉编码器的设计选择\n- 文档 OCR 与表格理解\n- 多模态 Agent 的构建\n- 实际案例分享与 Demo 演示',
  'sharing',
  'online',
  'upcoming',
  'online',
  'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80',
  '2026-04-02',
  '2026-04-02',
  '线上直播',
  'https://deepseek.club/sharing/multimodal',
  '深求社区',
  '',
  '[{"name":"吴佳琪","title":"多模态研究员","avatar":"","company":"DeepSeek"}]',
  '["多模态","VL模型","技术分享","OCR"]',
  3000,
  1245,
  '免费',
  '["前沿技术解析","实际案例演示","代码示例","实时互动"]',
  '[{"time":"20:00","title":"DeepSeek-VL2 架构解析","speaker":"吴佳琪"},{"time":"20:40","title":"实际应用案例分享","speaker":"吴佳琪"},{"time":"21:10","title":"Demo 演示与 Q&A"}]',
  '["DeepSeek"]',
  'https://deepseek.club/sharing/multimodal',
  1123,
  'approved'
);
INSERT INTO events (
  id, title, `desc`, full_desc, event_type, event_mode, event_status, city,
  cover_image, start_date, end_date, location, online_url, organizer, organizer_logo,
  speakers, tags, max_participants, current_participants, price,
  highlights, agenda, sponsors, registration_url,
  likes, approval_status
) VALUES (
  'deepseek-code-competition',
  'DeepSeek 代码挑战赛：AI 辅助编程大赛',
  '利用 DeepSeek-Coder 解决算法难题，展示人机协作编程的极限',
  'DeepSeek 代码挑战赛是一场创新的编程竞赛，参赛者需要利用 DeepSeek-Coder 系列模型辅助解决一系列算法和工程问题。比赛考察参赛者的 Prompt 工程能力、代码理解能力和人机协作效率。\n\n## 赛制说明\n- 个人赛，限时 4 小时\n- 10 道题目，难度递增\n- 允许使用 DeepSeek-Coder API\n- 按解题数量和用时排名',
  'competition',
  'online',
  'registering',
  'online',
  'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&q=80',
  '2026-04-12',
  '2026-04-12',
  '线上',
  'https://deepseek.club/competition/code-challenge',
  '深求社区 × LeetCode',
  '',
  '[{"name":"杨帆","title":"竞赛出题人","avatar":"","company":"LeetCode"}]',
  '["竞赛","编程","Coder","算法"]',
  2000,
  876,
  '免费',
  '["丰厚奖品","官方认证证书","企业直通面试","排行榜竞技"]',
  '[{"time":"09:00","title":"赛前说明与环境检查"},{"time":"09:30","title":"比赛正式开始"},{"time":"13:30","title":"比赛结束，提交代码"},{"time":"14:00","title":"成绩公布与颁奖"}]',
  '["DeepSeek","LeetCode","字节跳动"]',
  'https://deepseek.club/competition/code-challenge',
  1678,
  'approved'
);
INSERT INTO events (
  id, title, `desc`, full_desc, event_type, event_mode, event_status, city,
  cover_image, start_date, end_date, location, online_url, organizer, organizer_logo,
  speakers, tags, max_participants, current_participants, price,
  highlights, agenda, sponsors, registration_url,
  likes, approval_status
) VALUES (
  'beijing-ai-meetup-04',
  '北京 AI 开发者聚会 · 四月场',
  '北京本地开发者交流，主题：大模型微调与私有化部署实践',
  '北京 AI 开发者月度聚会四月场，本期聚焦大模型微调与私有化部署。三位嘉宾将分享在不同场景下微调 DeepSeek 模型的经验，以及私有化部署的最佳实践。',
  'meetup',
  'offline',
  'registering',
  'beijing',
  'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800&q=80',
  '2026-04-19',
  '2026-04-19',
  '北京·望京 SOHO',
  NULL,
  '深求社区北京分会',
  '',
  '[{"name":"马晓东","title":"AI 工程师","avatar":"","company":"某大厂"},{"name":"陈雅文","title":"MLOps 负责人","avatar":"","company":"某创业公司"}]',
  '["聚会","北京","微调","部署"]',
  60,
  45,
  '免费',
  '["实战经验分享","面对面交流","自由社交","精美茶歇"]',
  '[{"time":"14:00","title":"签到"},{"time":"14:30","title":"大模型微调实践","speaker":"马晓东"},{"time":"15:20","title":"私有化部署最佳实践","speaker":"陈雅文"},{"time":"16:00","title":"自由交流"}]',
  '["深求社区"]',
  'https://deepseek.club/meetup/beijing-04',
  389,
  'approved'
);
INSERT INTO events (
  id, title, `desc`, full_desc, event_type, event_mode, event_status, city,
  cover_image, start_date, end_date, location, online_url, organizer, organizer_logo,
  speakers, tags, max_participants, current_participants, price,
  highlights, agenda, sponsors, registration_url,
  likes, approval_status
) VALUES (
  'rag-workshop-advanced',
  '高级 RAG 工作坊：构建企业级知识库系统',
  '深入 RAG 技术栈，从向量数据库到混合检索，构建生产级知识库',
  '本工作坊面向有 RAG 基础的开发者，深入讲解企业级知识库系统的构建方法。涵盖高级检索策略、混合检索、重排序、多模态 RAG 等进阶主题。\n\n## 学习内容\n- 高级检索策略（HyDE、多查询、自适应检索）\n- 混合检索与重排序\n- 多模态 RAG（文档+图表）\n- 评估与优化方法\n- 生产环境部署与监控',
  'workshop',
  'online',
  'upcoming',
  'online',
  'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
  '2026-04-10',
  '2026-04-10',
  '线上直播',
  'https://deepseek.club/workshop/rag-advanced',
  '深求社区',
  '',
  '[{"name":"郑凯","title":"RAG 技术专家","avatar":"","company":"某向量数据库公司"}]',
  '["RAG","知识库","工作坊","企业级"]',
  200,
  156,
  '¥199',
  '["进阶内容","代码实操","企业案例","课后答疑"]',
  '[{"time":"09:30","title":"高级检索策略","speaker":"郑凯"},{"time":"11:00","title":"混合检索与重排序实战"},{"time":"14:00","title":"多模态 RAG 实践"},{"time":"15:30","title":"生产部署与监控"},{"time":"16:30","title":"Q&A 与课后答疑"}]',
  '["DeepSeek","Milvus"]',
  'https://deepseek.club/workshop/rag-advanced',
  723,
  'approved'
);
INSERT INTO events (
  id, title, `desc`, full_desc, event_type, event_mode, event_status, city,
  cover_image, start_date, end_date, location, online_url, organizer, organizer_logo,
  speakers, tags, max_participants, current_participants, price,
  highlights, agenda, sponsors, registration_url,
  likes, approval_status
) VALUES (
  'ai-safety-lecture',
  'AI 安全与对齐：开源模型的责任与挑战',
  '探讨开源大模型的安全风险、对齐技术与负责任的 AI 发展',
  '随着开源大模型的快速发展，AI 安全问题日益受到关注。本次讲座邀请了 AI 安全领域的研究者和从业者，深入探讨开源模型面临的安全挑战、对齐技术的最新进展，以及如何推动负责任的 AI 发展。',
  'lecture',
  'online',
  'ended',
  'online',
  'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80',
  '2026-03-10',
  '2026-03-10',
  '线上直播',
  'https://deepseek.club/lecture/ai-safety',
  '深求社区 × AI 安全联盟',
  '',
  '[{"name":"Prof. Liu Wei","title":"教授","avatar":"","company":"清华大学"},{"name":"张安琪","title":"AI 安全研究员","avatar":"","company":"DeepSeek"}]',
  '["AI安全","对齐","讲座","伦理"]',
  5000,
  4230,
  '免费',
  '["学术前沿","产业实践","政策解读","录播回放"]',
  '[{"time":"19:00","title":"开源模型的安全挑战","speaker":"Prof. Liu Wei"},{"time":"19:40","title":"对齐技术的最新进展","speaker":"张安琪"},{"time":"20:20","title":"圆桌讨论：负责任的 AI 发展"}]',
  '["DeepSeek","清华大学"]',
  'https://deepseek.club/lecture/ai-safety',
  2890,
  'approved'
);
INSERT INTO events (
  id, title, `desc`, full_desc, event_type, event_mode, event_status, city,
  cover_image, start_date, end_date, location, online_url, organizer, organizer_logo,
  speakers, tags, max_participants, current_participants, price,
  highlights, agenda, sponsors, registration_url,
  likes, approval_status
) VALUES (
  'startup-sharing-series',
  'AI 创业者说 · 第 12 期：从模型到产品',
  '三位 AI 创业者分享基于 DeepSeek 构建产品的创业历程',
  '「AI 创业者说」是深求社区的系列分享活动，每期邀请 AI 领域的创业者分享创业经验。本期三位嘉宾将分享他们如何基于 DeepSeek 模型构建产品，从技术选型到产品打磨，从融资到市场推广的全过程。',
  'sharing',
  'online',
  'ongoing',
  'online',
  'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&q=80',
  '2026-03-17',
  '2026-03-17',
  '线上直播',
  'https://deepseek.club/sharing/startup-12',
  '深求社区',
  '',
  '[{"name":"刘创","title":"创始人","avatar":"","company":"AI 教育公司"},{"name":"王芳","title":"CEO","avatar":"","company":"AI 写作工具"},{"name":"李鹏","title":"CTO","avatar":"","company":"AI 客服平台"}]',
  '["创业","分享","产品","经验"]',
  3000,
  2100,
  '免费',
  '["创业经验","产品思维","融资故事","实时互动"]',
  '[{"time":"20:00","title":"AI 教育产品的打磨之路","speaker":"刘创"},{"time":"20:25","title":"AI 写作工具的 PMF 之旅","speaker":"王芳"},{"time":"20:50","title":"AI 客服的企业落地","speaker":"李鹏"},{"time":"21:15","title":"圆桌讨论与 Q&A"}]',
  '["深求社区","创业邦"]',
  'https://deepseek.club/sharing/startup-12',
  1456,
  'approved'
);
INSERT INTO events (
  id, title, `desc`, full_desc, event_type, event_mode, event_status, city,
  cover_image, start_date, end_date, location, online_url, organizer, organizer_logo,
  speakers, tags, max_participants, current_participants, price,
  highlights, agenda, sponsors, registration_url,
  likes, approval_status
) VALUES (
  'fine-tuning-workshop',
  'DeepSeek 模型微调实战工作坊',
  '从数据准备到 LoRA 微调，手把手教你定制专属 AI 模型',
  '本工作坊面向希望定制专属 AI 模型的开发者和企业用户，全流程讲解 DeepSeek 模型微调的方法与实践。从数据准备、清洗到 LoRA/QLoRA 微调，再到评估和部署，提供完整的实操指导。',
  'workshop',
  'hybrid',
  'ended',
  'guangzhou',
  'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80',
  '2026-03-01',
  '2026-03-02',
  '广州·天河科技园 / 线上同步',
  'https://deepseek.club/workshop/fine-tuning',
  '深求社区 × 某云服务商',
  '',
  '[{"name":"何俊杰","title":"模型训练专家","avatar":"","company":"某云服务商"}]',
  '["微调","LoRA","工作坊","实战"]',
  100,
  100,
  '¥399',
  '["全流程实操","GPU 算力提供","1对1指导","结业证书"]',
  '[{"time":"Day1 09:00","title":"微调理论与数据准备","speaker":"何俊杰"},{"time":"Day1 14:00","title":"LoRA/QLoRA 实战"},{"time":"Day2 09:00","title":"评估与优化"},{"time":"Day2 14:00","title":"部署与上线"}]',
  '["DeepSeek","某云服务商"]',
  'https://deepseek.club/workshop/fine-tuning',
  1890,
  'approved'
);

-- ========= Seed: projects =========
INSERT INTO projects (
  id, name, full_name, category, description, long_description,
  language, stars, forks, issues, contributors, license,
  last_update, created_at, topics,
  github_url, website_url, logo_url,
  is_weekly_pick, is_editor_choice, editor_comment, trend_stars_7d,
  likes, approval_status
) VALUES (
  'vllm',
  'vLLM',
  'vllm-project/vllm',
  'inference',
  '高吞吐、低延迟的 LLM 推理与服务引擎，支持 PagedAttention 等先进内存管理技术',
  'vLLM 是一个快速且易用的 LLM 推理和服务库。它通过 PagedAttention 技术实现了高效的 KV Cache 内存管理，相比传统方案吞吐量提升 2-4 倍。\n\n**核心特性：**\n- PagedAttention：受操作系统虚拟内存启发的注意力算法，极大减少内存浪费\n- 连续批处理（Continuous Batching）：动态合并请求，最大化 GPU 利用率\n- 支持 CUDA/ROCm 多种硬件后端\n- 兼容 OpenAI API 协议，可作为 Drop-in 替换\n- 支持张量并行、流水线并行等分布式推理\n- 内置投机采样（Speculative Decoding）加速\n\n**适用场景：** 生产环境 LLM 服务部署、高并发 API 服务、模型性能基准测试',
  'Python',
  42800,
  6200,
  1850,
  680,
  'Apache-2.0',
  '2026-03-18',
  '2023-02-09',
  '["llm","inference","serving","paged-attention","cuda"]',
  'https://github.com/vllm-project/vllm',
  'https://vllm.ai',
  NULL,
  0,
  1,
  '生产环境 LLM 推理的事实标准，PagedAttention 技术革命性地解决了 KV Cache 内存碎片问题',
  320,
  0,
  'approved'
);
INSERT INTO projects (
  id, name, full_name, category, description, long_description,
  language, stars, forks, issues, contributors, license,
  last_update, created_at, topics,
  github_url, website_url, logo_url,
  is_weekly_pick, is_editor_choice, editor_comment, trend_stars_7d,
  likes, approval_status
) VALUES (
  'langchain',
  'LangChain',
  'langchain-ai/langchain',
  'rag',
  '构建基于 LLM 的应用程序框架，提供链式调用、RAG、Agent 等核心抽象',
  'LangChain 是构建 LLM 应用的主流框架，提供了从数据连接、提示模板、链式调用到 Agent 的完整工具链。\n\n**核心模块：**\n- LangChain Core：基础抽象与 LCEL 表达式语言\n- LangChain Community：第三方集成（向量数据库、文档加载器等）\n- LangGraph：有状态多步骤 Agent 编排\n- LangSmith：可观测性与评测平台\n\n**适用场景：** RAG 系统、对话机器人、文档问答、多步骤 Agent',
  'Python',
  98500,
  15800,
  2100,
  3200,
  'MIT',
  '2026-03-17',
  '2022-10-25',
  '["llm","rag","agent","chain","langchain"]',
  'https://github.com/langchain-ai/langchain',
  'https://langchain.com',
  NULL,
  1,
  0,
  NULL,
  580,
  0,
  'approved'
);
INSERT INTO projects (
  id, name, full_name, category, description, long_description,
  language, stars, forks, issues, contributors, license,
  last_update, created_at, topics,
  github_url, website_url, logo_url,
  is_weekly_pick, is_editor_choice, editor_comment, trend_stars_7d,
  likes, approval_status
) VALUES (
  'milvus',
  'Milvus',
  'milvus-io/milvus',
  'vector-db',
  '云原生向量数据库，专为十亿级向量相似度搜索而设计，支持混合搜索',
  'Milvus 是一个开源的云原生向量数据库，支持海量向量数据的存储、索引和管理。它被广泛用于 RAG、推荐系统、图像搜索等场景。\n\n**核心特性：**\n- 支持多种索引类型：IVF、HNSW、DiskANN 等\n- 混合搜索：向量 + 标量过滤\n- 水平扩展：分布式架构，支持十亿级数据\n- GPU 加速索引构建与搜索\n- 多语言 SDK：Python、Java、Go、Node.js\n\n**适用场景：** RAG 知识库、语义搜索、推荐系统、图像/音频检索',
  'Go',
  32600,
  3100,
  680,
  420,
  'Apache-2.0',
  '2026-03-16',
  '2019-10-15',
  '["vector-database","similarity-search","embedding","cloud-native"]',
  'https://github.com/milvus-io/milvus',
  'https://milvus.io',
  NULL,
  0,
  1,
  '向量数据库领域的标杆项目，云原生架构使其在大规模生产环境中表现出色',
  180,
  0,
  'approved'
);
INSERT INTO projects (
  id, name, full_name, category, description, long_description,
  language, stars, forks, issues, contributors, license,
  last_update, created_at, topics,
  github_url, website_url, logo_url,
  is_weekly_pick, is_editor_choice, editor_comment, trend_stars_7d,
  likes, approval_status
) VALUES (
  'llamacpp',
  'llama.cpp',
  'ggerganov/llama.cpp',
  'inference',
  '纯 C/C++ 实现的 LLM 推理，支持 CPU/GPU 混合推理与多种量化格式',
  'llama.cpp 让大语言模型可以在消费级硬件上高效运行。通过纯 C/C++ 实现和多种量化方案（GGUF 格式），它将 LLM 推理的门槛大幅降低。\n\n**核心特性：**\n- 支持 2/3/4/5/6/8-bit 量化\n- CPU + GPU 混合推理（CUDA、Metal、Vulkan）\n- GGUF 统一模型格式\n- 内置 HTTP Server（兼容 OpenAI API）\n- 支持多模态模型（LLaVA 等）\n\n**适用场景：** 本地 LLM 部署、边缘设备推理、隐私敏感场景',
  'C++',
  72300,
  10400,
  920,
  780,
  'MIT',
  '2026-03-18',
  '2023-03-10',
  '["llm","inference","quantization","gguf","cpp"]',
  'https://github.com/ggerganov/llama.cpp',
  NULL,
  NULL,
  1,
  0,
  NULL,
  450,
  0,
  'approved'
);
INSERT INTO projects (
  id, name, full_name, category, description, long_description,
  language, stars, forks, issues, contributors, license,
  last_update, created_at, topics,
  github_url, website_url, logo_url,
  is_weekly_pick, is_editor_choice, editor_comment, trend_stars_7d,
  likes, approval_status
) VALUES (
  'lmstudio',
  'Ollama',
  'ollama/ollama',
  'inference',
  '本地运行大语言模型的最简方案，一行命令即可启动 LLM 服务',
  'Ollama 让在本地运行大语言模型变得极其简单。它封装了 llama.cpp 等底层引擎，提供了类 Docker 的模型管理体验。\n\n**核心特性：**\n- 一行命令运行模型：ollama run llama3\n- 内置模型库，支持数百种开源模型\n- 自动硬件检测与优化\n- REST API 兼容 OpenAI 格式\n- 支持 Modelfile 自定义模型\n\n**适用场景：** 本地开发调试、隐私优先场景、离线部署',
  'Go',
  105000,
  8200,
  1200,
  450,
  'MIT',
  '2026-03-17',
  '2023-06-26',
  '["llm","local","inference","docker-like"]',
  'https://github.com/ollama/ollama',
  'https://ollama.com',
  NULL,
  0,
  0,
  NULL,
  890,
  0,
  'approved'
);
INSERT INTO projects (
  id, name, full_name, category, description, long_description,
  language, stars, forks, issues, contributors, license,
  last_update, created_at, topics,
  github_url, website_url, logo_url,
  is_weekly_pick, is_editor_choice, editor_comment, trend_stars_7d,
  likes, approval_status
) VALUES (
  'dify',
  'Dify',
  'langgenius/dify',
  'agent',
  '开源 LLM 应用开发平台，提供可视化 Workflow 编排、RAG 引擎和 Agent 框架',
  'Dify 是一个开源的 LLM 应用开发平台，让非技术人员也能通过可视化界面构建 AI 应用。\n\n**核心特性：**\n- 可视化 Workflow 编排引擎\n- 内置 RAG Pipeline（支持多种文档格式）\n- Agent 框架（Function Calling / ReAct）\n- 多模型支持（OpenAI、Anthropic、本地模型等）\n- 应用模板市场\n\n**适用场景：** 企业 AI 应用快速开发、内部知识库、客服机器人',
  'TypeScript',
  58600,
  8700,
  1560,
  620,
  'Apache-2.0',
  '2026-03-18',
  '2023-04-12',
  '["llm","agent","workflow","rag","no-code"]',
  'https://github.com/langgenius/dify',
  'https://dify.ai',
  NULL,
  0,
  1,
  '降低 AI 应用开发门槛的典范，可视化编排让复杂 Agent 流程变得直观',
  620,
  0,
  'approved'
);
INSERT INTO projects (
  id, name, full_name, category, description, long_description,
  language, stars, forks, issues, contributors, license,
  last_update, created_at, topics,
  github_url, website_url, logo_url,
  is_weekly_pick, is_editor_choice, editor_comment, trend_stars_7d,
  likes, approval_status
) VALUES (
  'unsloth',
  'Unsloth',
  'unslothai/unsloth',
  'finetune',
  '2-5x 更快的 LLM 微调，内存占用减少 80%，支持 LoRA/QLoRA',
  'Unsloth 通过手写 Triton 内核和智能内存优化，让 LLM 微调速度提升 2-5 倍，同时大幅降低显存需求。\n\n**核心特性：**\n- 手写 Triton 内核，无精度损失\n- 支持 LoRA、QLoRA、全参数微调\n- 显存占用减少 80%\n- 兼容 Hugging Face 生态\n- 支持 Llama、Mistral、Gemma 等主流模型\n\n**适用场景：** 消费级 GPU 上微调大模型、快速实验迭代',
  'Python',
  22400,
  1600,
  340,
  85,
  'Apache-2.0',
  '2026-03-15',
  '2023-11-01',
  '["finetune","lora","qlora","triton","efficient"]',
  'https://github.com/unslothai/unsloth',
  'https://unsloth.ai',
  NULL,
  1,
  0,
  NULL,
  340,
  0,
  'approved'
);
INSERT INTO projects (
  id, name, full_name, category, description, long_description,
  language, stars, forks, issues, contributors, license,
  last_update, created_at, topics,
  github_url, website_url, logo_url,
  is_weekly_pick, is_editor_choice, editor_comment, trend_stars_7d,
  likes, approval_status
) VALUES (
  'label-studio',
  'Label Studio',
  'HumanSignal/label-studio',
  'data',
  '多类型数据标注平台，支持文本、图像、音频、视频、时序等标注任务',
  'Label Studio 是一个灵活的开源数据标注工具，支持几乎所有类型的数据标注任务。\n\n**核心特性：**\n- 支持文本、图像、音频、视频、HTML、时序数据\n- 可自定义标注界面（XML 模板）\n- 内置 ML Backend 支持主动学习\n- 团队协作与质量管理\n- REST API 与 Python SDK\n\n**适用场景：** 训练数据准备、标注团队管理、主动学习流程',
  'Python',
  19800,
  2400,
  560,
  310,
  'Apache-2.0',
  '2026-03-14',
  '2020-02-18',
  '["annotation","labeling","data","nlp","computer-vision"]',
  'https://github.com/HumanSignal/label-studio',
  'https://labelstud.io',
  NULL,
  0,
  0,
  NULL,
  95,
  0,
  'approved'
);
INSERT INTO projects (
  id, name, full_name, category, description, long_description,
  language, stars, forks, issues, contributors, license,
  last_update, created_at, topics,
  github_url, website_url, logo_url,
  is_weekly_pick, is_editor_choice, editor_comment, trend_stars_7d,
  likes, approval_status
) VALUES (
  'mlflow',
  'MLflow',
  'mlflow/mlflow',
  'mlops',
  '端到端 ML 生命周期管理平台，覆盖实验追踪、模型注册、部署全流程',
  'MLflow 是 ML 生命周期管理的行业标准工具，由 Databricks 开源维护。\n\n**核心模块：**\n- MLflow Tracking：实验参数、指标、产物追踪\n- MLflow Models：统一模型打包格式\n- MLflow Registry：模型版本管理与审批\n- MLflow Projects：可复现的 ML 代码打包\n- MLflow Evaluate：LLM 评估框架\n\n**适用场景：** ML 实验管理、模型版本控制、生产部署流水线',
  'Python',
  19200,
  4300,
  780,
  850,
  'Apache-2.0',
  '2026-03-16',
  '2018-06-05',
  '["mlops","experiment-tracking","model-registry","deployment"]',
  'https://github.com/mlflow/mlflow',
  'https://mlflow.org',
  NULL,
  0,
  0,
  NULL,
  72,
  0,
  'approved'
);
INSERT INTO projects (
  id, name, full_name, category, description, long_description,
  language, stars, forks, issues, contributors, license,
  last_update, created_at, topics,
  github_url, website_url, logo_url,
  is_weekly_pick, is_editor_choice, editor_comment, trend_stars_7d,
  likes, approval_status
) VALUES (
  'langfuse',
  'Langfuse',
  'langfuse/langfuse',
  'monitoring',
  '开源 LLM 可观测性平台，提供追踪、评估、提示管理和成本分析',
  'Langfuse 是专为 LLM 应用设计的可观测性平台，帮助开发者理解和优化 AI 应用的行为。\n\n**核心特性：**\n- 分布式追踪：可视化 LLM 调用链路\n- 评估框架：自动化与人工评估结合\n- 提示管理：版本控制与 A/B 测试\n- 成本分析：Token 用量与费用追踪\n- 数据集管理：构建评测数据集\n\n**适用场景：** LLM 应用调试、性能优化、成本控制、质量监控',
  'TypeScript',
  8600,
  920,
  280,
  180,
  'MIT',
  '2026-03-17',
  '2023-05-15',
  '["observability","tracing","llm","evaluation","prompt-management"]',
  'https://github.com/langfuse/langfuse',
  'https://langfuse.com',
  NULL,
  1,
  0,
  'LLM 应用的「New Relic」，让 AI 系统的黑盒变透明',
  210,
  0,
  'approved'
);
INSERT INTO projects (
  id, name, full_name, category, description, long_description,
  language, stars, forks, issues, contributors, license,
  last_update, created_at, topics,
  github_url, website_url, logo_url,
  is_weekly_pick, is_editor_choice, editor_comment, trend_stars_7d,
  likes, approval_status
) VALUES (
  'ragas',
  'RAGAS',
  'explodinggradients/ragas',
  'eval',
  'RAG 系统评估框架，提供忠实度、相关性、上下文精确度等自动化指标',
  'RAGAS（Retrieval Augmented Generation Assessment）是专门评估 RAG 系统质量的框架。\n\n**核心指标：**\n- Faithfulness：生成内容对检索上下文的忠实度\n- Answer Relevancy：回答与问题的相关性\n- Context Precision：检索上下文的精确度\n- Context Recall：检索上下文的召回率\n\n**适用场景：** RAG 系统质量评估、检索策略对比、生成质量监控',
  'Python',
  8200,
  820,
  190,
  140,
  'Apache-2.0',
  '2026-03-13',
  '2023-07-10',
  '["rag","evaluation","metrics","llm","retrieval"]',
  'https://github.com/explodinggradients/ragas',
  'https://ragas.io',
  NULL,
  0,
  0,
  NULL,
  125,
  0,
  'approved'
);
INSERT INTO projects (
  id, name, full_name, category, description, long_description,
  language, stars, forks, issues, contributors, license,
  last_update, created_at, topics,
  github_url, website_url, logo_url,
  is_weekly_pick, is_editor_choice, editor_comment, trend_stars_7d,
  likes, approval_status
) VALUES (
  'crewai',
  'CrewAI',
  'crewAIInc/crewAI',
  'agent',
  '多 Agent 协作框架，通过角色扮演实现复杂任务的自动化分工与协作',
  'CrewAI 让多个 AI Agent 像团队一样协作完成复杂任务，每个 Agent 有独立的角色、目标和工具。\n\n**核心概念：**\n- Agent：具有角色、目标、背景故事的 AI 实体\n- Task：分配给 Agent 的具体任务\n- Crew：Agent 团队的编排与协调\n- Process：顺序执行或层级委派\n\n**适用场景：** 复杂工作流自动化、研究报告生成、多步骤数据处理',
  'Python',
  24800,
  3400,
  520,
  210,
  'MIT',
  '2026-03-16',
  '2023-12-01',
  '["agent","multi-agent","crew","automation","role-playing"]',
  'https://github.com/crewAIInc/crewAI',
  'https://crewai.com',
  NULL,
  0,
  0,
  NULL,
  380,
  0,
  'approved'
);
INSERT INTO projects (
  id, name, full_name, category, description, long_description,
  language, stars, forks, issues, contributors, license,
  last_update, created_at, topics,
  github_url, website_url, logo_url,
  is_weekly_pick, is_editor_choice, editor_comment, trend_stars_7d,
  likes, approval_status
) VALUES (
  'guardrails',
  'Guardrails AI',
  'guardrails-ai/guardrails',
  'security',
  'LLM 输出验证与结构化框架，确保 AI 生成内容的安全性和合规性',
  'Guardrails AI 提供了一套验证 LLM 输出的框架，帮助开发者确保 AI 生成内容符合预期。\n\n**核心特性：**\n- 输出格式验证（JSON Schema）\n- 内容安全检查（有害内容、PII 检测）\n- 自动重试与修正机制\n- 可组合的验证器（Validators）\n- 与主流 LLM 框架集成\n\n**适用场景：** 生产环境 LLM 输出质量保障、合规性检查、结构化输出',
  'Python',
  4800,
  380,
  145,
  95,
  'Apache-2.0',
  '2026-03-12',
  '2023-03-20',
  '["guardrails","validation","safety","structured-output","llm"]',
  'https://github.com/guardrails-ai/guardrails',
  'https://guardrailsai.com',
  NULL,
  0,
  0,
  NULL,
  65,
  0,
  'approved'
);
INSERT INTO projects (
  id, name, full_name, category, description, long_description,
  language, stars, forks, issues, contributors, license,
  last_update, created_at, topics,
  github_url, website_url, logo_url,
  is_weekly_pick, is_editor_choice, editor_comment, trend_stars_7d,
  likes, approval_status
) VALUES (
  'qdrant',
  'Qdrant',
  'qdrant/qdrant',
  'vector-db',
  '高性能 Rust 向量搜索引擎，支持过滤、负载和分布式部署',
  'Qdrant 是用 Rust 编写的高性能向量相似度搜索引擎，专注于生产级可靠性。\n\n**核心特性：**\n- Rust 实现，极致性能与内存安全\n- 丰富的过滤条件支持\n- 支持稀疏向量与多向量\n- 分布式集群部署\n- gRPC 与 REST API\n\n**适用场景：** 高性能语义搜索、推荐系统、多模态检索',
  'Rust',
  22100,
  1500,
  320,
  160,
  'Apache-2.0',
  '2026-03-17',
  '2021-05-18',
  '["vector-search","rust","similarity","distributed"]',
  'https://github.com/qdrant/qdrant',
  'https://qdrant.tech',
  NULL,
  0,
  1,
  'Rust 生态的向量数据库代表，性能与可靠性兼得',
  155,
  0,
  'approved'
);
INSERT INTO projects (
  id, name, full_name, category, description, long_description,
  language, stars, forks, issues, contributors, license,
  last_update, created_at, topics,
  github_url, website_url, logo_url,
  is_weekly_pick, is_editor_choice, editor_comment, trend_stars_7d,
  likes, approval_status
) VALUES (
  'llamaindex',
  'LlamaIndex',
  'run-llama/llama_index',
  'rag',
  'LLM 数据框架，将私有数据与大语言模型连接的桥梁',
  'LlamaIndex 专注于将各种数据源与 LLM 连接，是构建 RAG 应用的核心框架之一。\n\n**核心特性：**\n- 160+ 数据连接器（PDF、数据库、API 等）\n- 多种索引策略（向量、关键词、知识图谱）\n- 高级检索策略（混合搜索、重排序）\n- Agent 与工具集成\n- 可观测性与评估\n\n**适用场景：** 企业知识库、文档问答、数据分析 Agent',
  'Python',
  38900,
  5600,
  890,
  520,
  'MIT',
  '2026-03-18',
  '2022-11-02',
  '["rag","llm","data-framework","indexing","retrieval"]',
  'https://github.com/run-llama/llama_index',
  'https://llamaindex.ai',
  NULL,
  0,
  0,
  NULL,
  290,
  0,
  'approved'
);
INSERT INTO projects (
  id, name, full_name, category, description, long_description,
  language, stars, forks, issues, contributors, license,
  last_update, created_at, topics,
  github_url, website_url, logo_url,
  is_weekly_pick, is_editor_choice, editor_comment, trend_stars_7d,
  likes, approval_status
) VALUES (
  'trl',
  'TRL',
  'huggingface/trl',
  'finetune',
  'Transformer 强化学习库，支持 SFT、RLHF、DPO 等对齐训练方法',
  'TRL（Transformer Reinforcement Learning）是 Hugging Face 维护的对齐训练工具库。\n\n**支持的训练方法：**\n- SFT（Supervised Fine-Tuning）\n- RLHF（PPO 算法）\n- DPO（Direct Preference Optimization）\n- KTO、IPO 等新型对齐方法\n- 与 PEFT（LoRA）深度集成\n\n**适用场景：** 模型对齐训练、偏好学习、安全微调',
  'Python',
  11200,
  1400,
  260,
  220,
  'Apache-2.0',
  '2026-03-15',
  '2022-03-15',
  '["rlhf","dpo","alignment","sft","reinforcement-learning"]',
  'https://github.com/huggingface/trl',
  NULL,
  NULL,
  0,
  0,
  NULL,
  88,
  0,
  'approved'
);
INSERT INTO projects (
  id, name, full_name, category, description, long_description,
  language, stars, forks, issues, contributors, license,
  last_update, created_at, topics,
  github_url, website_url, logo_url,
  is_weekly_pick, is_editor_choice, editor_comment, trend_stars_7d,
  likes, approval_status
) VALUES (
  'phoenix',
  'Arize Phoenix',
  'Arize-ai/phoenix',
  'monitoring',
  'AI 可观测性与评估工具，支持 LLM 追踪、嵌入分析和实验管理',
  'Phoenix 是 Arize AI 开源的可观测性平台，帮助开发者监控和调试 AI 应用。\n\n**核心特性：**\n- OpenTelemetry 原生追踪\n- 嵌入向量可视化与漂移检测\n- LLM 评估（幻觉检测、相关性评分）\n- 实验管理与对比\n- 本地部署，数据不出域\n\n**适用场景：** LLM 应用调试、嵌入质量分析、模型漂移监控',
  'Python',
  7800,
  620,
  210,
  130,
  'Apache-2.0',
  '2026-03-14',
  '2023-03-01',
  '["observability","tracing","embeddings","evaluation"]',
  'https://github.com/Arize-ai/phoenix',
  'https://phoenix.arize.com',
  NULL,
  0,
  0,
  NULL,
  95,
  0,
  'approved'
);
INSERT INTO projects (
  id, name, full_name, category, description, long_description,
  language, stars, forks, issues, contributors, license,
  last_update, created_at, topics,
  github_url, website_url, logo_url,
  is_weekly_pick, is_editor_choice, editor_comment, trend_stars_7d,
  likes, approval_status
) VALUES (
  'haystack',
  'Haystack',
  'deepset-ai/haystack',
  'rag',
  '端到端 NLP/LLM 框架，用管道（Pipeline）抽象构建搜索与 RAG 系统',
  'Haystack 是 deepset 开源的 NLP 框架，以 Pipeline 为核心抽象构建搜索和 RAG 系统。\n\n**核心特性：**\n- 声明式 Pipeline 构建\n- 丰富的组件库（检索器、生成器、转换器）\n- 支持多种向量数据库后端\n- 内置评估框架\n- 可视化 Pipeline 编辑器\n\n**适用场景：** 企业搜索、文档问答、多模态 RAG',
  'Python',
  18500,
  2000,
  420,
  340,
  'Apache-2.0',
  '2026-03-16',
  '2019-11-14',
  '["rag","search","pipeline","nlp","retrieval"]',
  'https://github.com/deepset-ai/haystack',
  'https://haystack.deepset.ai',
  NULL,
  0,
  0,
  NULL,
  110,
  0,
  'approved'
);
